# Generated by Django 3.0.2 on 2024-05-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0003_auto_20240531_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='sex',
            new_name='sex_male',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='smoker',
            new_name='smoker_yes',
        ),
    ]
